name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
#<GENERATE_BEGIN>
  sim_at25df161:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_at25df161

  sim_basic:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_basic

  sim_cy15b104qs:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_cy15b104qs

  sim_cy15v104qs:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_cy15v104qs

  sim_m25p40:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_m25p40

  sim_m45pe80:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_m45pe80

  sim_s25fl064p:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_s25fl064p

  sim_s25fl512s:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_s25fl512s

  sim_s35hl256t:
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      name: sim_s35hl256t

#<GENERATE_END>
